// <auto-generated />
using System;
using BaseProjectAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BaseProjectAPI.Persistence.Migrations
{
    [DbContext(typeof(BaseDataContext))]
    [Migration("20210622170703_AddedUserSeed2")]
    partial class AddedUserSeed2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BaseProjectAPI.Domain.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTimeOffset(new DateTime(2014, 3, 22, 17, 6, 10, 982, DateTimeKind.Unspecified).AddTicks(9280), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Juana",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTimeOffset(new DateTime(2016, 5, 21, 9, 20, 23, 876, DateTimeKind.Unspecified).AddTicks(6498), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Kelli",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTimeOffset(new DateTime(2012, 12, 6, 20, 52, 46, 690, DateTimeKind.Unspecified).AddTicks(2521), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Sophie",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTimeOffset(new DateTime(2015, 3, 1, 0, 55, 25, 748, DateTimeKind.Unspecified).AddTicks(7293), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Louise",
                            Quantity = 8
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTimeOffset(new DateTime(2014, 8, 13, 3, 23, 53, 391, DateTimeKind.Unspecified).AddTicks(8699), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Traci",
                            Quantity = 9
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 6, 25, 4, 30, 25, 505, DateTimeKind.Unspecified).AddTicks(2432), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Alison",
                            Quantity = 9
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTimeOffset(new DateTime(2012, 5, 27, 3, 27, 9, 400, DateTimeKind.Unspecified).AddTicks(5467), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Christie",
                            Quantity = 7
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTimeOffset(new DateTime(2021, 2, 8, 9, 45, 56, 234, DateTimeKind.Unspecified).AddTicks(3179), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Elizabeth",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTimeOffset(new DateTime(2015, 12, 23, 0, 47, 30, 612, DateTimeKind.Unspecified).AddTicks(7101), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Angelica",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 8, 26, 15, 26, 55, 334, DateTimeKind.Unspecified).AddTicks(1416), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Rachel",
                            Quantity = 6
                        });
                });

            modelBuilder.Entity("BaseProjectAPI.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 3, 30, 20, 26, 34, 705, DateTimeKind.Unspecified).AddTicks(9877), new TimeSpan(0, -7, 0, 0, 0)),
                            Email = "Earnest_Runolfsdottir21@gmail.com",
                            FirstName = "Earnest",
                            IsEnabled = false,
                            LastName = "Runolfsdottir"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTimeOffset(new DateTime(2012, 4, 27, 15, 58, 52, 824, DateTimeKind.Unspecified).AddTicks(5992), new TimeSpan(0, -6, 0, 0, 0)),
                            Email = "Gabriel.Hirthe@gmail.com",
                            FirstName = "Gabriel",
                            IsEnabled = false,
                            LastName = "Hirthe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTimeOffset(new DateTime(2016, 6, 21, 0, 37, 40, 486, DateTimeKind.Unspecified).AddTicks(3629), new TimeSpan(0, -6, 0, 0, 0)),
                            Email = "Levi.Cummings5@hotmail.com",
                            FirstName = "Levi",
                            IsEnabled = true,
                            LastName = "Cummings"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTimeOffset(new DateTime(2014, 2, 27, 10, 56, 49, 820, DateTimeKind.Unspecified).AddTicks(2746), new TimeSpan(0, -7, 0, 0, 0)),
                            Email = "Cecil2@gmail.com",
                            FirstName = "Cecil",
                            IsEnabled = false,
                            LastName = "Koepp"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTimeOffset(new DateTime(2016, 5, 28, 15, 0, 36, 554, DateTimeKind.Unspecified).AddTicks(5502), new TimeSpan(0, -6, 0, 0, 0)),
                            Email = "Fernando_Goodwin92@gmail.com",
                            FirstName = "Fernando",
                            IsEnabled = false,
                            LastName = "Goodwin"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTimeOffset(new DateTime(2017, 2, 15, 17, 28, 1, 500, DateTimeKind.Unspecified).AddTicks(8706), new TimeSpan(0, -7, 0, 0, 0)),
                            Email = "Alfonso.Nolan@gmail.com",
                            FirstName = "Alfonso",
                            IsEnabled = false,
                            LastName = "Nolan"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 7, 3, 0, 42, 46, 701, DateTimeKind.Unspecified).AddTicks(7860), new TimeSpan(0, -6, 0, 0, 0)),
                            Email = "Alexander21@gmail.com",
                            FirstName = "Alexander",
                            IsEnabled = true,
                            LastName = "Mraz"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTimeOffset(new DateTime(2018, 6, 10, 13, 16, 44, 96, DateTimeKind.Unspecified).AddTicks(2352), new TimeSpan(0, -6, 0, 0, 0)),
                            Email = "Orlando26@gmail.com",
                            FirstName = "Orlando",
                            IsEnabled = false,
                            LastName = "Mitchell"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTimeOffset(new DateTime(2013, 7, 25, 6, 8, 4, 138, DateTimeKind.Unspecified).AddTicks(7320), new TimeSpan(0, -6, 0, 0, 0)),
                            Email = "Ron_Connelly@yahoo.com",
                            FirstName = "Ron",
                            IsEnabled = false,
                            LastName = "Connelly"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 4, 9, 20, 24, 38, 150, DateTimeKind.Unspecified).AddTicks(9647), new TimeSpan(0, -6, 0, 0, 0)),
                            Email = "Frederick.Lehner66@hotmail.com",
                            FirstName = "Frederick",
                            IsEnabled = true,
                            LastName = "Lehner"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
