// <auto-generated />
using System;
using BaseProjectAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BaseProjectAPI.Persistence.Migrations
{
    [DbContext(typeof(BaseDataContext))]
    [Migration("20210622164828_AddedUser")]
    partial class AddedUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BaseProjectAPI.Domain.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTimeOffset(new DateTime(2014, 3, 17, 5, 16, 26, 270, DateTimeKind.Unspecified).AddTicks(8102), new TimeSpan(0, -7, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2018, 12, 19, 9, 21, 41, 832, DateTimeKind.Unspecified).AddTicks(3441), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Miss Hector Schumm",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTimeOffset(new DateTime(2013, 11, 13, 11, 23, 15, 213, DateTimeKind.Unspecified).AddTicks(8553), new TimeSpan(0, -7, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2014, 9, 11, 13, 25, 34, 630, DateTimeKind.Unspecified).AddTicks(2580), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Lorena Rau I",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTimeOffset(new DateTime(2015, 3, 15, 15, 51, 25, 713, DateTimeKind.Unspecified).AddTicks(4830), new TimeSpan(0, -7, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2015, 6, 21, 22, 28, 26, 224, DateTimeKind.Unspecified).AddTicks(4441), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Iris Frami I",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTimeOffset(new DateTime(2012, 9, 7, 15, 44, 34, 876, DateTimeKind.Unspecified).AddTicks(4480), new TimeSpan(0, -6, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2012, 4, 15, 22, 5, 28, 107, DateTimeKind.Unspecified).AddTicks(8837), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Brandon Effertz I",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTimeOffset(new DateTime(2017, 1, 30, 17, 37, 43, 459, DateTimeKind.Unspecified).AddTicks(3079), new TimeSpan(0, -7, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2014, 12, 26, 4, 32, 50, 726, DateTimeKind.Unspecified).AddTicks(660), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Delores Heller II",
                            Quantity = 9
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTimeOffset(new DateTime(2017, 3, 10, 15, 0, 21, 19, DateTimeKind.Unspecified).AddTicks(7572), new TimeSpan(0, -7, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2017, 5, 5, 16, 58, 35, 303, DateTimeKind.Unspecified).AddTicks(7919), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Anita Dach DDS",
                            Quantity = 4
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTimeOffset(new DateTime(2020, 9, 22, 9, 20, 40, 486, DateTimeKind.Unspecified).AddTicks(1605), new TimeSpan(0, -6, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2015, 7, 21, 19, 9, 8, 885, DateTimeKind.Unspecified).AddTicks(6105), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Miss Penny Christiansen",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTimeOffset(new DateTime(2015, 11, 27, 23, 1, 39, 862, DateTimeKind.Unspecified).AddTicks(7354), new TimeSpan(0, -7, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2018, 4, 19, 6, 27, 48, 624, DateTimeKind.Unspecified).AddTicks(7752), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Ernest Reynolds Sr.",
                            Quantity = 4
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTimeOffset(new DateTime(2012, 4, 7, 12, 52, 54, 103, DateTimeKind.Unspecified).AddTicks(42), new TimeSpan(0, -6, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2017, 12, 2, 0, 49, 45, 453, DateTimeKind.Unspecified).AddTicks(8772), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Dr. Jackie Grimes",
                            Quantity = 9
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTimeOffset(new DateTime(2012, 6, 11, 1, 16, 41, 705, DateTimeKind.Unspecified).AddTicks(9902), new TimeSpan(0, -6, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2018, 2, 3, 14, 53, 16, 934, DateTimeKind.Unspecified).AddTicks(4877), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Erick Heller Sr.",
                            Quantity = 8
                        });
                });

            modelBuilder.Entity("BaseProjectAPI.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
