// <auto-generated />
using System;
using BaseProjectAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BaseProjectAPI.Persistence.Migrations
{
    [DbContext(typeof(BaseDataContext))]
    [Migration("20210617184930_Initw")]
    partial class Initw
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BaseProjectAPI.Domain.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DisabledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 6, 12, 2, 17, 31, 594, DateTimeKind.Unspecified).AddTicks(4628), new TimeSpan(0, -6, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2019, 2, 2, 4, 19, 48, 802, DateTimeKind.Unspecified).AddTicks(9589), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Miss Lori Keebler",
                            Quantity = 9
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTimeOffset(new DateTime(2020, 3, 3, 12, 50, 59, 244, DateTimeKind.Unspecified).AddTicks(6891), new TimeSpan(0, -7, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2021, 6, 3, 14, 53, 15, 104, DateTimeKind.Unspecified).AddTicks(3619), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Ms. Billie Huels",
                            Quantity = 8
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTimeOffset(new DateTime(2012, 6, 4, 10, 41, 27, 719, DateTimeKind.Unspecified).AddTicks(817), new TimeSpan(0, -6, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2013, 4, 26, 18, 12, 28, 68, DateTimeKind.Unspecified).AddTicks(5580), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Faith Hane MD",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 2, 21, 20, 36, 23, 518, DateTimeKind.Unspecified).AddTicks(6510), new TimeSpan(0, -7, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2018, 11, 3, 1, 42, 58, 636, DateTimeKind.Unspecified).AddTicks(6673), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Mrs. Joanna Wolff",
                            Quantity = 6
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTimeOffset(new DateTime(2013, 1, 24, 5, 43, 18, 469, DateTimeKind.Unspecified).AddTicks(3102), new TimeSpan(0, -7, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2019, 3, 23, 13, 43, 44, 802, DateTimeKind.Unspecified).AddTicks(7295), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Dr. Edmond Rohan",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTimeOffset(new DateTime(2016, 4, 20, 6, 16, 0, 343, DateTimeKind.Unspecified).AddTicks(9682), new TimeSpan(0, -6, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2013, 5, 23, 4, 46, 37, 833, DateTimeKind.Unspecified).AddTicks(9261), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Ms. Elizabeth Steuber",
                            Quantity = 6
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTimeOffset(new DateTime(2015, 4, 10, 9, 41, 35, 188, DateTimeKind.Unspecified).AddTicks(7201), new TimeSpan(0, -6, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2015, 11, 28, 14, 40, 57, 174, DateTimeKind.Unspecified).AddTicks(625), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Mrs. Kathy Kshlerin",
                            Quantity = 9
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTimeOffset(new DateTime(2016, 3, 14, 23, 41, 32, 936, DateTimeKind.Unspecified).AddTicks(3085), new TimeSpan(0, -7, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2020, 3, 1, 22, 27, 34, 460, DateTimeKind.Unspecified).AddTicks(2409), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Luther Hand II",
                            Quantity = 4
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTimeOffset(new DateTime(2011, 12, 13, 15, 19, 7, 217, DateTimeKind.Unspecified).AddTicks(3315), new TimeSpan(0, -7, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2012, 7, 3, 17, 13, 58, 656, DateTimeKind.Unspecified).AddTicks(3991), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Conrad Collins DDS",
                            Quantity = 9
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTimeOffset(new DateTime(2013, 12, 16, 16, 1, 9, 57, DateTimeKind.Unspecified).AddTicks(4091), new TimeSpan(0, -7, 0, 0, 0)),
                            DisabledOn = new DateTimeOffset(new DateTime(2020, 7, 18, 8, 45, 5, 331, DateTimeKind.Unspecified).AddTicks(9602), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Mrs. Ruby Connelly",
                            Quantity = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
