// <auto-generated />
using System;
using BaseProjectAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BaseProjectAPI.Persistence.Migrations
{
    [DbContext(typeof(BaseDataContext))]
    [Migration("20210622170328_AddedUserSeed")]
    partial class AddedUserSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("BaseProjectAPI.Domain.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTimeOffset(new DateTime(2015, 2, 24, 9, 34, 15, 811, DateTimeKind.Unspecified).AddTicks(194), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Barbara",
                            Quantity = 6
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTimeOffset(new DateTime(2012, 5, 1, 22, 14, 8, 203, DateTimeKind.Unspecified).AddTicks(3385), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Cecilia",
                            Quantity = 8
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTimeOffset(new DateTime(2015, 7, 29, 9, 10, 6, 791, DateTimeKind.Unspecified).AddTicks(4506), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Muriel",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTimeOffset(new DateTime(2013, 1, 23, 3, 36, 21, 999, DateTimeKind.Unspecified).AddTicks(4355), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Emma",
                            Quantity = 7
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTimeOffset(new DateTime(2013, 6, 18, 19, 22, 7, 947, DateTimeKind.Unspecified).AddTicks(8365), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Thelma",
                            Quantity = 6
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTimeOffset(new DateTime(2014, 2, 19, 15, 38, 35, 446, DateTimeKind.Unspecified).AddTicks(3367), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Jaime",
                            Quantity = 7
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTimeOffset(new DateTime(2018, 5, 26, 19, 0, 40, 381, DateTimeKind.Unspecified).AddTicks(6242), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Janice",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTimeOffset(new DateTime(2015, 1, 6, 4, 59, 44, 367, DateTimeKind.Unspecified).AddTicks(3687), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = false,
                            Name = "Johanna",
                            Quantity = 6
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTimeOffset(new DateTime(2016, 3, 12, 20, 7, 27, 877, DateTimeKind.Unspecified).AddTicks(4143), new TimeSpan(0, -7, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Kelley",
                            Quantity = 6
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTimeOffset(new DateTime(2019, 5, 25, 10, 15, 7, 227, DateTimeKind.Unspecified).AddTicks(36), new TimeSpan(0, -6, 0, 0, 0)),
                            IsEnabled = true,
                            Name = "Stella",
                            Quantity = 6
                        });
                });

            modelBuilder.Entity("BaseProjectAPI.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
