#!/bin/bash
# ===================================
# Server Environment Configuration Script
# ===================================
# This script helps configure environment variables for the BaseAPI
# on the Ubuntu server for production deployment
#
# Usage: sudo ./setup-server-env.sh

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

SERVICE_NAME="netcore-baseapi"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
ENV_FILE="/etc/baseapi/production.env"

echo -e "${CYAN}====================================${NC}"
echo -e "${CYAN}  BaseAPI Production Setup${NC}"
echo -e "${CYAN}====================================${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}? Please run as root (use sudo)${NC}"
    exit 1
fi

# Create secure directory for environment file
echo -e "${CYAN}===> Creating secure environment directory...${NC}"
mkdir -p /etc/baseapi
chmod 700 /etc/baseapi
echo -e "${GREEN}? Directory created${NC}"

# Function to prompt for input with default value
prompt_with_default() {
    local prompt="$1"
    local default="$2"
    local value
    
    if [ -z "$default" ]; then
        read -p "  $prompt: " value
    else
        read -p "  $prompt [$default]: " value
        value="${value:-$default}"
    fi
    
    echo "$value"
}

# Function to prompt for password
prompt_password() {
    local prompt="$1"
    local password
    local password_confirm
    
    while true; do
        read -sp "  $prompt: " password
        echo ""
        read -sp "  Confirm password: " password_confirm
        echo ""
        
        if [ "$password" = "$password_confirm" ]; then
            echo "$password"
            return
        else
            echo -e "${RED}  ? Passwords do not match. Try again.${NC}"
        fi
    done
}

echo ""
echo -e "${CYAN}===> Database Configuration${NC}"
DB_HOST=$(prompt_with_default "Database Host" "localhost")
DB_PORT=$(prompt_with_default "Database Port" "5432")
DB_NAME=$(prompt_with_default "Database Name" "BaseApiDb_Prod")
DB_USERNAME=$(prompt_with_default "Database Username" "baseapi_user")
DB_PASSWORD=$(prompt_password "Database Password")

echo ""
echo -e "${CYAN}===> Application Configuration${NC}"
ASPNETCORE_ENVIRONMENT=$(prompt_with_default "Environment" "Production")
ASPNETCORE_URLS=$(prompt_with_default "Application URLs" "http://localhost:5000")

echo ""
echo -e "${CYAN}===> Creating environment file...${NC}"

# Create the environment file with secure permissions
cat > "$ENV_FILE" <<EOF
# BaseAPI Production Environment Configuration
# Generated: $(date)
# DO NOT EDIT THIS FILE MANUALLY - Use setup-server-env.sh

# Database Configuration
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

# Application Configuration
ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
ASPNETCORE_URLS=${ASPNETCORE_URLS}
DOTNET_PRINT_TELEMETRY_MESSAGE=false

# Connection String (automatically built from above)
ConnectionStrings__DefaultConnection=Host=\${DB_HOST};Database=\${DB_NAME};Username=\${DB_USERNAME};Password=\${DB_PASSWORD};Port=\${DB_PORT};Pooling=true;

# Logging Configuration (optional - can be configured in appsettings.json)
# Logging__LogLevel__Default=Warning
# Logging__LogLevel__Microsoft.AspNetCore=Warning
# Logging__LogLevel__Microsoft.EntityFrameworkCore=Error
EOF

# Secure the environment file
chmod 600 "$ENV_FILE"
chown root:root "$ENV_FILE"

echo -e "${GREEN}? Environment file created at ${ENV_FILE}${NC}"

# Update systemd service to use the environment file
echo ""
echo -e "${CYAN}===> Updating systemd service...${NC}"

if [ ! -f "$SERVICE_FILE" ]; then
    echo -e "${YELLOW}??  Service file not found at ${SERVICE_FILE}${NC}"
    echo -e "${YELLOW}   Creating new service file...${NC}"
    
    # Get the user to run the service as
    SERVICE_USER=$(prompt_with_default "Service User" "www-data")
    APP_PATH=$(prompt_with_default "Application Path" "/var/www/netcore-baseapi")
    
    cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=BaseAPI .NET Core Application
After=network.target

[Service]
WorkingDirectory=${APP_PATH}
ExecStart=/usr/bin/dotnet ${APP_PATH}/BaseAPI.dll
Restart=always
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=${SERVICE_NAME}
User=${SERVICE_USER}
EnvironmentFile=${ENV_FILE}

[Install]
WantedBy=multi-user.target
EOF
    
    echo -e "${GREEN}? Service file created${NC}"
else
    # Check if EnvironmentFile is already configured
    if grep -q "EnvironmentFile=" "$SERVICE_FILE"; then
        echo -e "${YELLOW}??  EnvironmentFile already configured in service${NC}"
    else
        # Backup the original service file
        cp "$SERVICE_FILE" "${SERVICE_FILE}.backup"
        echo -e "${GREEN}? Backed up service file to ${SERVICE_FILE}.backup${NC}"
        
        # Add EnvironmentFile to service
        sed -i "/\[Service\]/a EnvironmentFile=${ENV_FILE}" "$SERVICE_FILE"
        echo -e "${GREEN}? Added EnvironmentFile to service configuration${NC}"
    fi
fi

# Reload systemd
echo ""
echo -e "${CYAN}===> Reloading systemd daemon...${NC}"
systemctl daemon-reload
echo -e "${GREEN}? Systemd daemon reloaded${NC}"

# Display service configuration
echo ""
echo -e "${CYAN}===> Current Service Configuration:${NC}"
systemctl cat "$SERVICE_NAME" | grep -A 20 "\[Service\]"

echo ""
echo -e "${GREEN}====================================${NC}"
echo -e "${GREEN}  ? Setup Complete!${NC}"
echo -e "${GREEN}====================================${NC}"
echo ""
echo -e "${CYAN}Next Steps:${NC}"
echo -e "  1. Test the configuration:"
echo -e "     ${YELLOW}sudo -u \$USER bash -c 'source ${ENV_FILE} && echo \$DB_HOST'${NC}"
echo ""
echo -e "  2. Restart the service:"
echo -e "     ${YELLOW}sudo systemctl restart ${SERVICE_NAME}${NC}"
echo ""
echo -e "  3. Check service status:"
echo -e "     ${YELLOW}sudo systemctl status ${SERVICE_NAME}${NC}"
echo ""
echo -e "  4. View logs:"
echo -e "     ${YELLOW}sudo journalctl -u ${SERVICE_NAME} -f${NC}"
echo ""
echo -e "${CYAN}Configuration Files:${NC}"
echo -e "  Environment: ${ENV_FILE}"
echo -e "  Service:     ${SERVICE_FILE}"
echo ""
echo -e "${YELLOW}??  Security Note:${NC}"
echo -e "  The environment file is secured with 600 permissions (owner read/write only)"
echo -e "  Only root can read this file"
echo ""

# Offer to restart the service
read -p "Would you like to restart the ${SERVICE_NAME} service now? (y/n): " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${CYAN}===> Restarting ${SERVICE_NAME} service...${NC}"
    systemctl restart "$SERVICE_NAME"
    sleep 2
    systemctl status "$SERVICE_NAME" --no-pager
fi
